platform :ios, '9.0' #最低适配版本

source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftTest' do
  
  if ENV['local']
    pod 'FlutterSDKDebug', :path => '../../../Flutter/my_flutter'
  else
    pod 'FlutterSDKDebug', '0.1.0'
  end
  
  pod 'AFNetworking', '3.2.1'
end
